//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AirSide.ServerModules.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class as_assetStatusProfile
    {
        public int id { get; set; }
        public int i_assetProfileId { get; set; }
        public bool bt_assetStatus { get; set; }
        public int i_assetSeverity { get; set; }
        public System.DateTime dt_lastUpdated { get; set; }
    }
}
