//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AirSide.ServerModules.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class as_eventTypes
    {
        public int i_eventId { get; set; }
        public string vc_title { get; set; }
        public string vc_description { get; set; }
        public string vc_color { get; set; }
        public string vc_icon { get; set; }
        public string vc_userId { get; set; }
    }
}
