//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AirSide.ServerModules.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class as_fileUploadInfo
    {
        public System.Guid guid_file { get; set; }
        public string vc_description { get; set; }
        public double f_latitude { get; set; }
        public double f_longitude { get; set; }
        public int i_shiftId { get; set; }
        public int i_userId_logged { get; set; }
        public bool bt_resolved { get; set; }
        public int i_userId_resolved { get; set; }
        public int i_severityId { get; set; }
        public System.DateTime dt_dateTimeResolved { get; set; }
    }
}
