//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AirSide.ServerModules.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class as_photometricProfile
    {
        public System.Guid id { get; set; }
        public System.DateTime dateOfRun { get; set; }
        public int assetId { get; set; }
        public int maxIntensity { get; set; }
        public int averageIntensity { get; set; }
        public int icaoPercentage { get; set; }
        public string pictureUrl { get; set; }
    }
}
