//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AirSide.ServerModules.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class as_reportParameters
    {
        public int i_reportParamId { get; set; }
        public string vc_parameterName { get; set; }
        public string vc_dataType { get; set; }
        public int i_reportId { get; set; }
    }
}
