//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AirSide.ServerModules.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class as_shiftData
    {
        public int i_uniqueId { get; set; }
        public int i_shiftId { get; set; }
        public int i_assetId { get; set; }
        public int i_maintenanceId { get; set; }
        public string vc_dateStamp { get; set; }
        public System.DateTime dt_captureDate { get; set; }
        public double f_capturedValue { get; set; }
        public int i_assetCheckId { get; set; }
    }
}
