//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AirSide.ServerModules.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class as_settingsProfile
    {
        public int i_settingId { get; set; }
        public string vc_settingDescription { get; set; }
        public int i_dataType { get; set; }
        public bool bt_active { get; set; }
        public string vc_settingValue { get; set; }
    }
}
