//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AirSide.ServerModules.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class as_todoProfile
    {
        public int i_todoProfileId { get; set; }
        public System.DateTime dt_dateTime { get; set; }
        public string vc_description { get; set; }
        public int i_todoCatId { get; set; }
        public bool bt_active { get; set; }
        public bool bt_private { get; set; }
        public int UserId { get; set; }
        public System.DateTime dt_completedDate { get; set; }
    }
}
