//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ADB.AirSide.Encore.V1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class as_assetClassProfile
    {
        public int i_assetClassId { get; set; }
        public string vc_description { get; set; }
        public int i_pictureId { get; set; }
        public string vc_manufacturer { get; set; }
        public string vc_model { get; set; }
        public int i_frequencyId { get; set; }
    }
}
