//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ADB.AirSide.Encore.V1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class as_assetProfile
    {
        public int i_assetId { get; set; }
        public int i_locationId { get; set; }
        public int i_assetClassId { get; set; }
        public string vc_rfidTag { get; set; }
        public string vc_serialNumber { get; set; }
    }
}
