//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ADB.AirSide.Encore.V1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class as_cacheProfile
    {
        public int i_cacheId { get; set; }
        public string vc_module { get; set; }
        public System.Guid ui_currentHash { get; set; }
        public bool bt_active { get; set; }
    }
}
