//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ADB.AirSide.Encore.V1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class as_fileUploadProfile
    {
        public int i_fileUploadId { get; set; }
        public System.Guid guid_file { get; set; }
        public string vc_filePath { get; set; }
        public string vc_fileDescription { get; set; }
        public int i_fileType { get; set; }
        public System.DateTime dt_datetime { get; set; }
    }
}
