//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ADB.AirSide.Encore.V1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class as_fbTechProfile
    {
        public int i_fbTechId { get; set; }
        public int i_assetId { get; set; }
        public int i_fbTechNumber { get; set; }
        public double f_averageCandela { get; set; }
        public double f_maxCandela { get; set; }
        public double f_persentageICAO { get; set; }
        public double f_verticalDegree { get; set; }
        public double f_horizontalDegree { get; set; }
        public double f_xAxis { get; set; }
        public double f_yAxis { get; set; }
        public int i_pictureId { get; set; }
        public System.DateTime dt_dateTimeStamp { get; set; }
        public bool bt_pass { get; set; }
    }
}
