//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ADB.AirSide.Encore.V1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class as_iosLogProfile
    {
        public int i_iosLogId { get; set; }
        public System.DateTime dt_logCaptureDate { get; set; }
        public int UserId { get; set; }
        public string vc_logContainer { get; set; }
        public string vc_logName { get; set; }
        public string vc_deviceUID { get; set; }
    }
}
