//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ADB.AirSide.Encore.V1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class as_iosImageProfile
    {
        public int i_iosImageId { get; set; }
        public System.DateTime dt_dateTimeStamp { get; set; }
        public string vc_description { get; set; }
        public string vc_version { get; set; }
        public bool bt_active { get; set; }
        public string vc_fileName { get; set; }
    }
}
