//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ADB.AirSide.Encore.V1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class as_logProfile
    {
        public int i_logId { get; set; }
        public string vc_logDescription { get; set; }
        public System.DateTime dt_dateTimeStamp { get; set; }
        public int i_logType { get; set; }
    }
}
