//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ADB.AirSide.Encore.V1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class as_maintenanceValidationProfile
    {
        public int i_maintenanceValidationProfileId { get; set; }
        public int i_maintenanceProfileId { get; set; }
        public int i_maintenanceValidationId { get; set; }
    }
}
