//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ADB.AirSide.Encore.V1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class as_shifts
    {
        public int i_shiftId { get; set; }
        public int UserId { get; set; }
        public System.DateTime dt_scheduledDate { get; set; }
        public System.DateTime dt_completionDate { get; set; }
        public bool bt_completed { get; set; }
        public int i_areaSubId { get; set; }
        public string vc_permitNumber { get; set; }
        public int i_maintenanceId { get; set; }
    }
}
