//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ADB.AirSide.Encore.V1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class as_shiftsCustomProfile
    {
        public int i_shiftCustomProfileId { get; set; }
        public int i_shiftCustomId { get; set; }
        public int i_assetId { get; set; }
    }
}
